name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

module:
  androidX: true

environment:
  sdk: '>=3.3.0-279.2.beta <4.0.0'

dependencies:
  cloud_firestore: ^4.15.5
  flutter:
    sdk: flutter
  hive:
  hive_flutter:




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator:
  build_runner:
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
    
  

